# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: java_build
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        #run: mvn sonar:sonar -Dsonar.projectKey=ankit20000_DevSecops_Pipeline -Dsonar.organization=ankit20000 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3efd906389f89ff2f42493c5bda21481a0a75a68
        run: mvn sonar:sonar -Dsonar.projectKey=sra-1_DevSecops_Pipeline -Dsonar.organization=sra-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=70f7cfd4f75aac6471c786cf1743ab2f5c50a1bb
